repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the latest version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      - id: check-added-large-files

  # - repo: https://github.com/psf/black
  #   rev: 22.3.0 # Replace with the latest version of black
  #   hooks:
  #     - id: black
  #       language_version: python3.10 # Ensure compatibility with your Python version

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1 # Replace with the latest version of flake8
    hooks:
      - id: flake8
