version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - ./.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - db

  nginx: 
    build: ./nginx
    # ports: configuration pour tests en local
    #   - 8687:80
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
    restart: "always"

volumes:
  static_volume:
  postgres_data:
