version: '3.8'

services:

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

  web:
    build: .
    command: python manage.py runserver localhost:8000
    volumes:
      - ./portfolio/:/usr/src/portfolio/
    ports:
      - 8000:8000
    env_file:
      - ./.env

volumes:
  postgres_data: