version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

  web:
    build: .
    image: dimitrihoareau/portfolio
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - ./.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - web
    restart: "always"

volumes:
  static_volume:
  media_volume: 
  postgres_data:


