# Generated by Django 3.2.25 on 2024-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='Untitled.png', upload_to='project_pictures'),
        ),
    ]
