# Generated by Django 3.2.25 on 2024-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_project_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(to='mainpage.Tool'),
        ),
    ]
