# name: Quality Assurance

# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: python:3.11.4-slim-buster

#     services:
#       db:
#         image: postgres:16
#         environment:
#           POSTGRES_USER: portfolio
#           POSTGRES_PASSWORD: portfolio
#           POSTGRES_DB: portfolio

#     steps:
#       - uses: actions/checkout@v2

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Run tests
#         run: pytest

name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        CSRF_TRUSTED_ORIGINS: "https://dimitrihoareau.fr"
      run: |
        pytest
